#!/bin/bash
source coinlist
source config

for coins in "${coinlist[@]}"; do
    coin=($coins)
    if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]]; then
        echo ${coin[0]}
        $komodocli -ac_name=${coin[0]} $1 $2 $3 $4 $5 $6 $7 $8 $9
    fi
done
