#!/bin/bash
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

for coins in "${coinlist[@]}"; do
    coin=($coins)
    if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]]; then
        echo ${coin[0]}
        $komodocli -ac_name=${coin[0]} "$@"
    fi
done
