#!/bin/bash
#
# Checks that your addresses are imported
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

function validateaddress ()
{
    ismine=$($komodocli $2 validateaddress $1 | jq .ismine)
    if [[ ! -z $2 ]]; then
        echo "[${2}] ${ismine}"
    else
        echo "[KMD] ${ismine}"
    fi
}

validateaddress $nn_address

novalidateaddress=('AYA')

if (( thirdpartycoins < 1 )); then
    for coins in "${coinlist[@]}"; do
        coin=($coins)
        if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]]; then
            validateaddress $nn_address -ac_name=${coin[0]}
        fi
    done
else
    for coins in "${coinsthird[@]}"; do
        coin=($coins)

        if [[ ${komodolike[*]} =~ ${coin[0]} ]]; then
            coinaddress=${nn_address}
            coincli="${komodocli} -ac_name=${coin[0]^^}"
        else
            coinaddress=$(eval echo "\${${coin[0],,}_address-}")
            eval $(echo coincli=${coin[1]})
        fi

        if [[ ${novalidateaddress[*]} =~ ${coin[0]} ]]; then
            ismine=$(${coincli} getaddressinfo ${coinaddress} | jq .ismine)
        else
            ismine=$(${coincli} validateaddress ${coinaddress} | jq .ismine)
        fi
        echo "[${coin[0]}] ${ismine}"
    done
fi
