#!/bin/bash
#
# @author webworker01
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $scriptpath/coinlist
source $scriptpath/config

$komodocli cleanwallettransactions

if (( thirdpartycoins < 1 )); then
    for coins in "${coinlist[@]}"; do
        coin=($coins)
        if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]]; then
            echo ${coin[0]}
            $komodocli -ac_name=${coin[0]} cleanwallettransactions
        fi
    done
fi
