#!/bin/bash
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

freqten=('VRSC')
freqtwo=('KMDICE')
sleeptime=3

if [[ ! -z $1 ]]; then
    case "$1" in
        GAME|EMC2)
            log "dpow" "Start ${1} Freq 5"
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"GAME\",\"freq\":5,\"pubkey\":\"${nn_pubkey}\"}"
            ;;
        VRSC)
            log "dpow" "Start ${1} Freq 10"
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"freq\":10,\"pubkey\":\"${nn_pubkey}\"}"
            ;;
        KMDICE)
            log "dpow" "Start ${1} Freq 2"
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"freq\":2,\"pubkey\":\"${nn_pubkey}\"}"
            ;;
        *)
            log "dpow" "Start ${1} Freq Default"
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"pubkey\":\"${nn_pubkey}\"}"
            ;;
    esac
else

    if (( thirdpartycoins < 1 )); then
        for coins in "${coinlist[@]}"; do
            coin=($coins)

            if [[ ${freqten[*]} =~ ${coin[0]} ]]; then
                log "dpow" "Start ${coin[0]} Freq 10"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${coin[0]}\",\"freq\":10,\"pubkey\":\"${nn_pubkey}\"}"
            elif [[ ${freqtwo[*]} =~ ${coin[0]} ]]; then
                log "dpow" "Start ${coin[0]} Freq 2"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${coin[0]}\",\"freq\":2,\"pubkey\":\"${nn_pubkey}\"}"
            else
                log "dpow" "Start ${coin[0]} Freq Default"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${coin[0]}\",\"pubkey\":\"${nn_pubkey}\"}"
            fi
            sleep $sleeptime
        done

    else
        log "dpow" "Start CHIPS Freq Default"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"CHIPS\",\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        log "dpow" "Start EMC2 Freq 5"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"EMC2\",\"freq\":5,\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        log "dpow" "Start VRSC Freq Default"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"VRSC\",\"freq\":10,\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        log "dpow" "Start AYA Freq Default"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"AYA\",\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        log "dpow" "Start MCL Freq Default"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"MCL\",\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        log "dpow" "Start GLEEC Freq Default"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"GLEEC\",\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        log "dpow" "Start PBC Freq Default"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"PBC\",\"pubkey\":\"${nn_pubkey}\"}"
    fi
fi
