#!/bin/bash
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

freqfive=('AYA' 'EMC2' 'MIL')
sleeptime=3

if [[ ! -z $1 ]]; then
    if [[ ${freqfive[*]} =~ ${1} ]]; then
        log "dpow" "Start ${1} Freq 5"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"freq\":5,\"pubkey\":\"${nn_pubkey}\"}"
    else
        log "dpow" "Start ${1} Freq Default"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"pubkey\":\"${nn_pubkey}\"}"
    fi
else
    if (( $thirdpartycoins < 1 )); then
        dpowlist="coinlist[@]"
    else
        dpowlist="coinsthird[@]"
    fi

    for coins in "${!dpowlist}"; do
        coin=($coins)
        cointostart=${coin[0]}

        if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]] && [[ ! ${skipnotarize[*]} =~ ${coin[0]} ]]; then
            if [[ ${freqfive[*]} =~ ${coin[0]} ]]; then
                log "dpow" "Start ${coin[0]} Freq 5"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${cointostart}\",\"freq\":5,\"pubkey\":\"${nn_pubkey}\"}"
            else
                log "dpow" "Start ${coin[0]} Freq Default"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${cointostart}\",\"pubkey\":\"${nn_pubkey}\"}"
            fi
            sleep $sleeptime
        fi
    done
fi
