#!/bin/bash
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source ${scriptpath}/config
source ${scriptpath}/coinlist

freqten=('RFOX VRSC')
freqtwo=('KMDICE')
sleeptime=1

if [[ ! -z $1 ]]; then
    case "$1" in
        GAME|EMC2)
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"GAME\",\"freq\":5,\"pubkey\":\"${nn_pubkey}\"}"
            ;;
        RFOX|VRSC)
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"freq\":10,\"pubkey\":\"${nn_pubkey}\"}"
            ;;
        KMDICE)
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"freq\":2,\"pubkey\":\"${nn_pubkey}\"}"
            ;;
        *)
            curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"$1\",\"pubkey\":\"${nn_pubkey}\"}"
            ;;
    esac
else

    if (( thirdpartycoins < 1 )); then
        for coins in "${coinlist[@]}"; do
            coin=($coins)

            echo "--DPOW: ${coin[0]}--"
            if [[ ${freqten[*]} =~ ${coin[0]} ]]; then
                echo "Freq 10"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${coin[0]}\",\"freq\":10,\"pubkey\":\"${nn_pubkey}\"}"
            elif [[ ${freqtwo[*]} =~ ${coin[0]} ]]; then
                echo "Freq 2"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${coin[0]}\",\"freq\":2,\"pubkey\":\"${nn_pubkey}\"}"
            else
                echo "Freq Default"
                curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"${coin[0]}\",\"pubkey\":\"${nn_pubkey}\"}"
            fi
            sleep $sleeptime
        done
    else
        echo "--DPOW: CHIPS--"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"CHIPS\",\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        echo "--DPOW: GAME--"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"GAME\",\"freq\":5,\"pubkey\":\"${nn_pubkey}\"}"
        sleep $sleeptime
        echo "--DPOW: EMC2--"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"EMC2\",\"freq\":5,\"pubkey\":\"${nn_pubkey}\"}"
        echo "--DPOW: GIN--"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"GIN\",\"pubkey\":\"${nn_pubkey}\"}"
        echo "--DPOW: VRSC--"
        curl --url "http://127.0.0.1:${iguanaport}" --data "{\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"VRSC\",\"freq\":10,\"pubkey\":\"${nn_pubkey}\"}"
    fi
fi
