#!/bin/bash
#
# @author webworker01
#
source coinlist
source config

if [[ -z $1 ]]; then
    echo "Usage ./importkey <keytoimport>"
    exit 0
fi

for coins in "${coinlist[@]}"; do
    coin=($coins)
    echo ${coin[0]}
    $komodocli -ac_name=${coin[0]} importprivkey $1 "" false
done
