#!/bin/bash
# init for notary node required dependencies and repos
# setup config file first to indicate 1st or 3rd party server
# after setup you will still need to create wp_7776/wp_7779 file
#
# Usage: ./init <include any param value to run without sudo commands>
#
# @see https://docs.komodoplatform.com/notary/setup-Komodo-Notary-Node.html#create-wp-7776
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ ! -z $1 ]]; then
    nosudo=0
else
    nosudo=1
fi

if (( nosudo > 0 )); then
    #dependencies
    sudo apt-get update && sudo apt-get upgrade -y
    sudo apt-get install libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev python-zmq zlib1g-dev wget curl bsdmainutils automake cmake clang libsodium-dev libcurl4-gnutls-dev libssl-dev git unzip python jq htop -y
    #nanomsg
    cd $HOME
    git clone https://github.com/nanomsg/nanomsg
    cd nanomsg
    cmake . -DNN_TESTS=OFF -DNN_ENABLE_DOC=OFF
    make -j2
    sudo make install
    sudo ldconfig
fi

#komodo
cd $HOME
git clone https://github.com/KomodoPlatform/komodo
cd komodo && git checkout e159b4e7a40d3886519401c4074e957a1f9d42ba
$scriptpath/rebuildkomodo
$HOME/komodo/zcutil/fetch-params.sh

if (( nosudo > 0 )); then
    sudo ln -sf /home/$USER/komodo/src/komodo-cli /usr/local/bin/komodo-cli
    sudo ln -sf /home/$USER/komodo/src/komodod /usr/local/bin/komodod
fi

#create komodo.conf
randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
cd $HOME

if (( thirdpartycoins < 1 )); then
    blocknotify="blocknotify=$HOME/nntools/minerfixer %s"
fi

mkdir -p $HOME/.komodo
cat <<EOF > $HOME/.komodo/komodo.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=7771
$blocknotify
EOF
chmod 600 $HOME/.komodo/komodo.conf

echo "pubkey=$nn_pubkey" > $HOME/komodo/src/pubkey.txt

#Iguana
cd $HOME
git clone https://github.com/KomodoPlatform/dPoW -b master --single-branch
cd dPoW
# git checkout beta_season3
cp $HOME/komodo/src/pubkey.txt $HOME/dPoW/iguana/pubkey.txt

if (( thirdpartycoins < 1 )); then
    #bitcoin
    cd $HOME
    git clone https://github.com/bitcoin/bitcoin
    cd bitcoin
    git checkout 0.16
    $scriptpath/rebuildbitcoin
    if (( nosudo > 0 )); then
        sudo ln -sf /home/$USER/bitcoin/src/bitcoin-cli /usr/local/bin/bitcoin-cli
        sudo ln -sf /home/$USER/bitcoin/src/bitcoind /usr/local/bin/bitcoind
    fi

    #bitcoin.conf
    randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    cd $HOME
    mkdir -p $HOME/.bitcoin
    cat <<EOF > $HOME/.bitcoin/bitcoin.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
listen=0
listenonion=0
onlynet=ipv4
deprecatedrpc=estimatefee
EOF
    chmod 600 $HOME/.bitcoin/bitcoin.conf

else
    #CHIPS
    cd $HOME
    git clone https://github.com/jl777/chips3
    cd chips3
    git checkout 31d59f9d8fa4a8e00dd474ef0561a5b174056d86
    $scriptpath/rebuildchips

    #chips.conf
    randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    cd $HOME
    mkdir -p $HOME/.chips
    cat <<EOF > $HOME/.chips/chips.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
deprecatedrpc=signrawtransaction
EOF
    chmod 600 $HOME/.chips/chips.conf

    #EMC2
    cd ~
    git clone https://github.com/emc2foundation/einsteinium
    cd einsteinium
    git checkout 70d7dc2b94e0b275f026ae51fda2a23725929bfd
    $scriptpath/rebuildemc2

    #einsteinium.conf
    randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    cd $HOME
    mkdir -p $HOME/.einsteinium
    cat <<EOF > $HOME/.einsteinium/einsteinium.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
listen=0
listenonion=0
onlynet=ipv4
EOF
    chmod 600 $HOME/.einsteinium/einsteinium.conf

    #VRSC
    cd $HOME
    git clone https://github.com/VerusCoin/VerusCoin
    cd VerusCoin && git checkout d3cffbe
    ./zcutil/build.sh -j$(expr $(nproc) - 1)

    #AYA
    cd $HOME
    git clone https://github.com/KomodoPlatform/AYAv2
    cd AYAv2
    git pull
    git checkout 3d03bdf
    $scriptpath/rebuildaya

    mkdir -p ~/.aryacoin

    #aryacoin.conf
    randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    cd $HOME
    mkdir -p $HOME/.aryacoin
    cat <<EOF > $HOME/.aryacoin/aryacoin.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
litemode=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
listen=0
listenonion=0
onlynet=ipv4
maxconnections=8
EOF
    chmod 600 $HOME/.aryacoin/aryacoin.conf

    #Marmara
    cd $HOME
    git clone https://github.com/marmarachain/Marmara-v.1.0.git
    cd Marmara-v.1.0 && git checkout 03dd780
    ./zcutil/build.sh -j$(expr $(nproc) - 1)

    #GleecBTC
    cd $HOME
    git clone https://github.com/KomodoPlatform/GleecBTC-FullNode-Win-Mac-Linux.git
    cd GleecBTC-FullNode-Win-Mac-Linux
    git checkout b4ffcc9
    $scriptpath/rebuildgleecbtc

    #gleecbtc.conf
    randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    cd $HOME
    mkdir -p $HOME/.gleecbtc
    cat <<EOF > $HOME/.gleecbtc/gleecbtc.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
deprecatedrpc=signrawtransaction
rpcport=18332
listen=0
listenonion=0
onlynet=ipv4
EOF
    chmod 600 $HOME/.gleecbtc/gleecbtc.conf

    #PowerBlockCoin
    cd $HOME
    git clone https://github.com/pbcllc/powerblockcoin-core
    cd powerblockcoin-core
    git checkout 51f456a
    $scriptpath/rebuildpbc

    #powerblockcoin.conf
    randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    cd $HOME
    mkdir -p $HOME/.powerblockcoin
    cat <<EOF > $HOME/.powerblockcoin/powerblockcoin.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
deprecatedrpc=signrawtransaction
listen=0
listenonion=0
onlynet=ipv4
EOF
    chmod 600 $HOME/.powerblockcoin/powerblockcoin.conf
fi

echo
echo "Done! You must create wp_7776 or wp_7779 file https://docs.komodoplatform.com/notary/setup-Komodo-Notary-Node.html#create-wp-7776 and import your private keys"
