#!/bin/bash
# init for notary node required dependencies and repos
# setup config file first to indicate 1st or 3rd party server
# after setup you will still need to create wp_7776/wp_7779 file
#
# Usage: ./init <include any param value to run without sudo commands>
#
# @see https://docs.komodoplatform.com/notary/setup-Komodo-Notary-Node.html#create-wp-7776
# @author webworker01
#
set -e

scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if [[ ! -z $1 ]]; then
    usesudo=0
else
    usesudo=1
fi

if (( usesudo > 1 )); then
    #dependencies
    sudo apt-get update && sudo apt-get upgrade -y
    sudo apt-get install libevent-dev build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev zlib1g-dev wget curl bsdmainutils automake cmake clang libsodium-dev libcurl4-gnutls-dev libssl-dev git unzip python python3 python3-zmq jq htop -y

    #nanomsg
    if [[ ! -d "$HOME/nanomsg" ]]; then
        cd $HOME
        git clone https://github.com/nanomsg/nanomsg
        cd nanomsg
        cmake . -DNN_TESTS=OFF -DNN_ENABLE_DOC=OFF
        make -j$(expr $(nproc) - 1)
        sudo make install
        sudo ldconfig
    else
        echo "$HOME/nanomsg already exists, continuing..."
    fi
fi

#komodo
if [[ ! -d "$HOME/komodo" ]]; then
    cd $HOME
    git clone https://github.com/KomodoPlatform/komodo
    cd komodo
    $HOME/komodo/zcutil/fetch-params-alt.sh
    $scriptpath/build kmd

    if (( usesudo > 0 )); then
        sudo ln -sf /home/$USER/komodo/src/komodo-cli /usr/local/bin/komodo-cli
        sudo ln -sf /home/$USER/komodo/src/komodod /usr/local/bin/komodod
    fi

    #create komodo.conf
    randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

    if (( thirdpartycoins < 1 )); then
        blocknotify="blocknotify=$HOME/nntools/minerfixer %s"
    fi

    mkdir -p $HOME/.komodo
    cat <<EOF > $HOME/.komodo/komodo.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=7771
$blocknotify
EOF
    chmod 600 $HOME/.komodo/komodo.conf

    echo "pubkey=$nn_pubkey" > $HOME/komodo/src/pubkey.txt
else
    echo "$HOME/komodo already exists, continuing..."
fi

#Iguana
if [[ ! -d "$HOME/dPoW" ]]; then
    cd $HOME
    git clone https://github.com/KomodoPlatform/dPoW -b master --single-branch
    cd dPoW
    # git checkout beta_season3
    cp $HOME/komodo/src/pubkey.txt $HOME/dPoW/iguana/pubkey.txt
else
    echo "$HOME/dPoW already exists, continuing..."
fi

if (( thirdpartycoins < 1 )); then
    #litecoin
    if [[ ! -d "$HOME/litecoin" ]]; then
        cd $HOME
        git clone https://github.com/litecoin-project/litecoin.git -b 0.16 --single-branch
        $scriptpath/build ltc

        #litecoin.conf
        randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

        mkdir -p $HOME/.litecoin
        cat <<EOF > $HOME/.litecoin/litecoin.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=9332
listen=0
listenonion=0
onlynet=ipv4
# deprecatedrpc=estimatefee
# maxmempool=500
EOF
        chmod 600 $HOME/.litecoin/litecoin.conf
    else
        echo "$HOME/litecoin already exists, continuing..."
    fi

else
    #CHIPS
    if [[ ! -d "$HOME/chips3" ]]; then
        cd $HOME
        git clone https://github.com/jl777/chips3
        cd chips3
        git checkout b57fd92
        $scriptpath/build chips

        #chips.conf
        randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

        mkdir -p $HOME/.chips
        cat <<EOF > $HOME/.chips/chips.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
deprecatedrpc=signrawtransaction
EOF
        chmod 600 $HOME/.chips/chips.conf
    else
        echo "$HOME/chips3 already exists, continuing..."
    fi

    #EMC2
    if [[ ! -d "$HOME/einsteinium" ]]; then
        cd $HOME
        git clone https://github.com/emc2foundation/einsteinium
        cd einsteinium
        git checkout 70d7dc2
        $scriptpath/build emc2

        #einsteinium.conf
        randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

        mkdir -p $HOME/.einsteinium
        cat <<EOF > $HOME/.einsteinium/einsteinium.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
listen=0
listenonion=0
onlynet=ipv4
EOF
        chmod 600 $HOME/.einsteinium/einsteinium.conf
    else
        echo "$HOME/einsteinium already exists, continuing..."
    fi

    #VRSC
    if [[ ! -d "$HOME/VerusCoin" ]]; then
        cd $HOME
        git clone https://github.com/VerusCoin/VerusCoin
        cd VerusCoin
        git checkout d3cffbe
        $scriptpath/build vrsc
    else
        echo "$HOME/VerusCoin already exists, continuing..."
    fi

    #AYA
    if [[ ! -d "$HOME/AYAv2" ]]; then
        cd $HOME
        git clone https://github.com/KomodoPlatform/AYAv2
        cd AYAv2
        git checkout 3d03bdf
        $scriptpath/build aya

        #aryacoin.conf
        randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

        mkdir -p $HOME/.aryacoin
        cat <<EOF > $HOME/.aryacoin/aryacoin.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
litemode=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
listen=0
listenonion=0
onlynet=ipv4
maxconnections=8
EOF
        chmod 600 $HOME/.aryacoin/aryacoin.conf
    else
        echo "$HOME/AYAv2 already exists, continuing..."
    fi

    #Marmara
    if [[ ! -d "$HOME/Marmara-v.1.0" ]]; then
        cd $HOME
        git clone https://github.com/marmarachain/Marmara-v.1.0.git
        cd Marmara-v.1.0
        git checkout 03dd780
        $scriptpath/build mcl
    else
        echo "$HOME/Marmara-v.1.0 already exists, continuing..."
    fi

    #GleecBTC
    if [[ ! -d "$HOME/GleecBTC-FullNode-Win-Mac-Linux" ]]; then
        cd $HOME
        git clone https://github.com/KomodoPlatform/GleecBTC-FullNode-Win-Mac-Linux.git
        cd GleecBTC-FullNode-Win-Mac-Linux
        git checkout b4ffcc9
        $scriptpath/build gleec

        #gleecbtc.conf
        randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        cd $HOME
        mkdir -p $HOME/.gleecbtc
        cat <<EOF > $HOME/.gleecbtc/gleecbtc.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
deprecatedrpc=signrawtransaction
rpcport=18332
listen=0
listenonion=0
onlynet=ipv4
EOF
        chmod 600 $HOME/.gleecbtc/gleecbtc.conf
    else
        echo "$HOME/GleecBTC-FullNode-Win-Mac-Linux already exists, continuing..."
    fi

    #SFUSD
    if [[ ! -d "$HOME/sfusd-core" ]]; then
        cd $HOME
        git clone https://github.com/pbcllc/sfusd-core.git
        cd sfusd-core
        git checkout 7c4f40b
        $scriptpath/build sfusd

        #sfusd.conf
        randusername=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        randpassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        cd $HOME
        mkdir -p $HOME/.smartusd
        cat <<EOF > $HOME/.smartusd/smartusd.conf
rpcuser=user$randusername
rpcpassword=pass$randpassword
txindex=1
server=1
daemon=1
rpcworkqueue=256
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
deprecatedrpc=signrawtransaction
listen=0
listenonion=0
onlynet=ipv4
EOF
        chmod 600 $HOME/.smartusd/smartusd.conf
    else
        echo "$HOME/sfusd-core already exists, continuing..."
    fi
fi

echo
echo "Done! You must create wp_7776 or wp_7779 file https://docs.komodoplatform.com/notary/setup-Komodo-Notary-Node.html#create-wp-7776 and import your private keys"
