#!/bin/bash
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

sudo apt-get install ufw

sudo ufw disable
sudo ufw default deny incoming

sudo ufw allow 22    comment 'SSH'
sudo ufw allow 7770  comment 'KMD'
if (( thirdpartycoins < 1 )); then
    #sudo ufw allow 8333  comment 'BTC'
    sudo ufw allow 17773 comment 'Iguana Notary Main'

    for coins in "${coinlist[@]}"; do
        coin=($coins)

        if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]]; then
            acport=$($komodocli -ac_name=${coin[0]} getinfo | jq .p2pport)
            echo $acport
            sudo ufw allow $acport comment "${coin[0]}"
        fi
    done
else
    sudo ufw allow 17774 comment 'Iguana Notary Third Party'
    sudo ufw allow 57777 comment 'CHIPS'
    #sudo ufw allow 40002 comment 'GAME'
    #sudo ufw allow 41878 comment 'EMC2'
    #sudo ufw allow 10111 comment 'GIN'
    sudo ufw allow 27485 comment 'VRSC'
fi

sudo ufw enable

# check the status again
sudo ufw status
