#!/bin/bash
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

sudo apt-get install ufw

sudo ufw disable
sudo ufw default deny incoming

sudo ufw allow 22    comment 'SSH'
sudo ufw allow 7770  comment 'KMD'
if (( thirdpartycoins < 1 )); then
    #sudo ufw allow 8333  comment 'BTC'
    if (( nn_season == 6 )); then
        port=13347
    else
        port=13337
    fi
    sudo ufw allow ${port} comment 'Iguana Notary Main'

    for coins in "${coinlist[@]}"; do
        coin=($coins)

        if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]]; then
            acport=$($komodocli -ac_name=${coin[0]} getinfo | jq .p2pport)
            echo $acport
            sudo ufw allow ${acport}/tcp comment "${coin[0]}"
        fi
    done
else
    if (( nn_season == 6 )); then
        port=13344
    else
        port=13334
    fi
    sudo ufw allow ${port}/tcp comment 'Iguana Notary Third Party'
    sudo ufw allow 26001/tcp comment 'AYA'
    sudo ufw allow 57777/tcp comment 'CHIPS'
    sudo ufw allow 41878/tcp comment 'EMC2'
    sudo ufw allow 33824/tcp comment 'MCL'
    sudo ufw allow 27485/tcp comment 'VRSC'
    sudo ufw allow 29404/tcp comment 'TOKEL'
    sudo ufw allow 38890/tcp comment 'MM2 P2P'
    sudo ufw allow 41888/tcp comment 'MIL'
    sudo ufw allow 47777/tcp comment 'SFUSD'
fi

sudo ufw enable

# check the status again
sudo ufw status
