#!/bin/bash
#
# Common startup for all scripts
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

#exit if no config
if [[ ! -f "${scriptpath}/config" ]]; then
    echo "You must setup a config file. See config.example"
    exit 1
fi

#imports
source ${scriptpath}/config

#config defaults if not set
addnodes=${addnodes:="-addnode=seed.komodostats.com -addnode=seed.webworker.sh"}
datetime=${datetime:=$(date '+%Y-%m-%d %H:%M:%S')}
dpowseeds=${dpowseeds:=('95.213.238.100' '77.75.121.138' '103.6.12.105' '139.99.209.214')}
txfeeperkb=${txfeeperkb:=0.000035}
sctxfeeperkb=${sctxfeeperkb:=0}
ltcutxoqty=${ltcutxoqty:=100}
pubkey=${nn_pubkey}
nn_season=${nn_season:=6}
skip_whitelist=${skip_whitelist:=('VOTE2022')}
miner_threads=${miner_threads:=1}

#more imports
source ${scriptpath}/coinlist
source ${scriptpath}/paths
source ${scriptpath}/functions
source ${scriptpath}/functions-wallet
