#!/bin/bash
# blocknotify script to disable mining when notary not eligible for easy mining
#
# Add to ~/.komodo/komodo.conf:
#
# blocknotify=/home/komodo/nntools/minerfixer %s
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

#disable until new consensus logic is analyzed
if (( nn_season == 6 )); then
    exit 0
fi

lastgen=$($komodocli listtransactions "*" 777 | jq '[.[] | select(.generated==true)] | .[-1]')
if [[ "$lastgen" != "null" ]]; then
    confirmations=$(jq .confirmations <<< $lastgen)
    rawconfirmations=$(jq .rawconfirmations <<< $lastgen)
    lastamount=$(jq .amount <<< $lastgen)
    lasthash=$(jq -r .blockhash <<< $lastgen)
    lasttxid=$(jq -r .txid <<< $lastgen)
    lastheight=$($komodocli getblockheader $lasthash | jq -r .height)

    log "minerfixer" "Last Amt:${lastamount} Ht:${lastheight} RawConfs:${rawconfirmations} Confs:${confirmations}" "green" "echo"

    if (( $rawconfirmations == 1 )); then
        log "minerfixer" "[[ Block found! ]] Height: ${lastheight} Amount: ${lastamount} TxID: ${lasttxid}" "red"

    elif (( $rawconfirmations == 2 )); then
        log "minerfixer" "[[ Block found! ]]" "green" "echo"

    #between 3 and 64 confirmations go into power saving mode
    elif (( ($rawconfirmations > 2 && $rawconfirmations < 65) )); then
        $komodocli setgenerate false

        if (( $rawconfirmations == 3 )); then
            log "minerfixer" "energy saving mode" "green"
        else
            log "minerfixer" "energy saving mode" "green" "echo"
        fi

    #setgenerate true upon eligibility and every 65 blocks after that as failsafe
    elif (( $rawconfirmations % 65 == 0 )); then
        log "minerfixer" "setgenerate true (${rawconfirmations} confs)"
        $komodocli setgenerate true 1

    # Verify mining when it should be
    else
        mining=$($komodocli getmininginfo | jq -r .generate)
        if [[ "${mining}" == "false" ]]; then
            log "minerfixer" "Should have been mining but wasn't - setgenerate true" "red"
            $komodocli setgenerate true 1
        else
            log "minerfixer" "mining.." "green" "echo"
        fi
    fi
else
    getsynced=$($komodocli getinfo | jq .synced)

    # Check if synced
    if [[ "$getsynced" != "null" && "$getsynced" == "true" ]]; then
        log "minerfixer" "could not get last mined tx! setgenerate true"
        $komodocli setgenerate true 1
    fi
fi
