#!/bin/bash
# Used to define paths for coin daemons
#
# @author webworker01
#

#declare non komodo clis - set the full path accessible as the second part of each string, the 3rd entry is the name of the data dir for the coin and assumes they are in $HOME
coinsfirst=(
'BTC $HOME/bitcoin/src/bitcoin-cli $HOME/bitcoin/src/bitcoind .bitcoin'
)

coinsthird=(
'CHIPS $HOME/chips3/src/chips-cli $HOME/chips3/src/chipsd .chips'
'GAME $HOME/GameCredits/src/gamecredits-cli $HOME/GameCredits/src/gamecreditsd .gamecredits'
'EMC2 $HOME/einsteinium/src/einsteinium-cli $HOME/einsteinium/src/einsteiniumd .einsteinium'
'GIN $HOME/gincoin-core/src/gincoin-cli $HOME/gincoin-core/src/gincoind .gincoincore'
'VRSC $HOME/VerusCoin/src/verus $HOME/VerusCoin/src/verusd .komodo/VRSC'
)

#for git checking - path and remote branch
declare -A repos=(
[KMD]="$HOME/komodo origin/beta"
[SUPERNET]="$HOME/dPoW origin/master"
[CHIPS]="$HOME/chips3 origin/dev"
[GAME]="$HOME/GameCredits origin/master"
[EMC2]="$HOME/einsteinium origin/master"
[GIN]="$HOME/gincoin-core origin/master"
[VRSC]="$HOME/VerusCoin origin/master"
)
