#!/bin/bash
berkeleydb () {
    LITECOIN_ROOT=$(pwd)
    LITECOIN_PREFIX="${LITECOIN_ROOT}/db4"
    mkdir -p $LITECOIN_PREFIX
    wget -N 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
    echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef db-4.8.30.NC.tar.gz' | sha256sum -c
    tar -xzvf db-4.8.30.NC.tar.gz
    cd db-4.8.30.NC/build_unix/

    ../dist/configure -enable-cxx -disable-shared -with-pic -prefix=$LITECOIN_PREFIX

    make install
    cd $LITECOIN_ROOT
}

buildLITECOIN () {
    git pull
    make clean
    ./autogen.sh
    ./configure LDFLAGS="-L${LITECOIN_PREFIX}/lib/" CPPFLAGS="-I${LITECOIN_PREFIX}/include/" --with-gui=no --disable-tests --disable-bench --without-miniupnpc --enable-experimental-asm --enable-static --disable-shared
    make -j$(nproc)
}

cd ~/litecoin
berkeleydb
buildLITECOIN

