#!/bin/bash
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

if (( thirdpartycoins < 1 )); then
    log "start" "Starting KMD"
    $komodod -gen -genproclimit=1 -notary -pubkey=$nn_pubkey $addnodes &

    for coins in "${coinsfirst[@]}"; do
        coin=($coins)
        cd $scriptpath/7776/
        log "start" "Starting ${coin[0]}"
        eval $(echo coinexec=${coin[2]})
        $coinexec -pubkey=$nn_pubkey $addnodes &
    done

    ./assetchains
else
    log "start" "Starting KMD"
    $komodod -pubkey=$nn_pubkey $addnodes &

    for coins in "${coinsthird[@]}"; do
        coin=($coins)
        log "start" "Starting ${coin[0]}"
        eval $(echo coinexec=${coin[2]})
        $coinexec -pubkey=$nn_pubkey $addnodes &
    done
fi
