#!/bin/bash
source config
source paths

$komodod -pubkey=$nn_pubkey $addnodes &

for coins in "${coinsthird[@]}"; do
    coin=($coins)
    echo "Starting ${coin[0]}"
    eval $(echo coinexec=${coin[2]})
    $coinexec -pubkey=$nn_pubkey $addnodes &
done
