#!/bin/bash
#
# @author webworker01
#
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scriptpath/main

pkill -15 komodod
pkill -15 iguana

if (( thirdpartycoins < 1 )); then
    pkill -15 bitcoind
else
    for coins in "${coinsthird[@]}"; do
        coin=($coins)
        echo "Stopping ${coin[0]}"
        eval $(echo coinexec=${coin[1]})
        $coinexec stop &
    done
fi
