#!/bin/bash
source config
source paths

pkill -15 komodod
pkill -15 iguana

for coins in "${coinsthird[@]}"; do
    coin=($coins)
    echo "Stopping ${coin[0]}"
    eval $(echo coinexec=${coin[1]})
    $coinexec stop &
done
